title: World Line
author:
    name: 'Adrian Petrescu'
    url:  https://twitter.com/apetresc
    email: apetresc@gmail.com
description: >
  Write an awesome description for your new site here.
baseurl: /
url: "http://blog.apetre.sc/"

github:
    repo: https://github.com/apetresc/blog.apetre.sc
twitter_username: apetresc
github_username:  apetresc

permalink: pretty

paginate: 5

# Build settings
markdown: redcarpet
highlighter: pygments

gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
